version: '3'

services:
  proxy:
    # this will use the latest version of 1.13.x
    image: nginx:1.13
    ports:
      # expose 80 on host and sent to 80 in container
      - '80:80'
    volumes:
      # It is 'bind mounting' the file with read only permission (that is why it ends with :ro)
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    # this will use httpd:latest
    image: httpd
