version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports: 
      - "8080:80"

    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  drupal-postgres:
    image: postgres:9.6

    secrets:
      - psql_user
      - psql_pass

    environment:
      POSTGRES_USER_FILE: /run/secrets/psql_user
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass

    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

#
# Here we need to inform that the secrets will be external and provided 
# by command line cli.
#
secrets:
  psql_user:
    external: true
  psql_pass:
    external: true