version: '2'

# It is the same command as:
# docker run -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  # A friendly name for the container. Also the DNS name inside a network.
  jekyll:
    # Setting image to use on https://hub.docker.com
    image: bretfisher/jekyll-serve
    volumes:
    # Maping volumes
      - .:/site
    # Mapping exposed ports
    ports:
      - '80:4000'
